### ISSUE TITLE
Site is awesome

### ISSUE THREAD

**Issue by Sandile-Dev01** [danehobrecht/www.danehobrecht.com#1]
I love the idea behind the site, it's awesome knowledge-giving but in terms of UI (User interface) and UX  (User experience), there's still room for improvement.

- The videos embedded are great but they would've appealed better if they were correctly aligned.
- Your slider is awesome but it doesn't respond to my hand gestures, this is not good for UX.
- I think the image where you sign autographs looks good and the text next to it is informative, but you can just spice it up with some `font-styles` to give contrast between the names of the plays you participated in and the general text.
- Your form is simple and not that good-looking, it's great on mobile but on tablets to 4K screens it's off.

**Comment by danehobrecht** [comment]
Hi Sandile,

I really appreciate the feedback. I went ahead and tackled the second bullet point and I'm tinkering with the third and fourth, but I was wondering if you could elaborate on the first? Could you provide screenshots of the incorrect alignment you're seeing? Thanks again Sandile.
